---
- name: Configurar servidor da aplicação
  hosts: web
  become: true

  vars_files:
    - vault.yml

  tasks:
    - name: Instalar Docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Iniciar e habilitar Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Adicionar ec2-user ao grupo docker
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: true

    - name: Instalar Python e pip
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
        state: present

    - name: Instalar SDK Docker para Python
      ansible.builtin.dnf:
        name: python3-docker
        state: present

    - name: Executar container da aplicação
      community.docker.docker_container:
        name: getting-started-app
        image: docker/getting-started
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:80"